name:  Build and Deploy web api to Azure

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        id: github
        uses: actions/Checkout@v4

      - name: Setup WebApi >NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{vars.ACR_SERVER}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}