name:  Build and Deploy web api to Azure

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        id: github
        uses: actions/Checkout@v4

      - name: Setup WebApi >NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{vars.ACR_SERVER}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}

      - name: SHA from commit
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short ${{github.sha}})" >> "$GITHUB_OUTPUT"

      - name: Build and push docker image to ACR
        env:
          ACR_REGISTRY: ${{vars.ACR_SERVER}}
          IMAGE_TAG: ${{steps.vars.outputs.short_sha}}
        run: |
          docker build -f MasterNet.Dockerfile \
            -t $ACR_REGISTRY/netapp:$IMAGE_TAG \
            -t $ACR_REGISTRY/netapp:latest \
        .
        docker push $ACR_REGISTRY/netapp --all-tags